### ISSUE TITLE
Oi, Cameron

### ISSUE THREAD

**Issue by changok** [camertron/grape-client-generator#2]
Since I'm not a contributor, I can't make code change :(
Can you update README doc for not suggesting to use set(:name, 'blah') ?
set method is deprecated since grape ver 0.10

**Comment by camertron** [comment]
Hey @changok, I can remove that line in the README, but anyone who uses this gem will have to provide some way of naming each endpoint. Is there a way to do that with recent versions of grape?

**Comment by changok** [comment]
Yup, but it's new syntax. You can provide it by using "named" in desc block.
For example,

```
desc 'Description for endpoint' do
  named 'the endpoint'
end
```

Collecting name from "named" is done by latest Yang's commit. So, you don't have to make any code change for this :)

**Comment by camertron** [comment]
Gotcha, I'll make the README change :)
